// src/products.js
const products = [
    {
        id: 1,
        name: "Bagged Full Flavor 200",
        price: 35,
        info: "Cigarettes, Bagged, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 2,
        name: "Bagged Lights 200",
        price: 35,
        info: "Cigarettes, Bagged, Light Cigarettes, Rated 0 out of 5, In stock",
    },
    {
        id: 3,
        name: "BB Full Cigarettes",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 4,
        name: "BB Lights Cigarettes",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 5,
        name: "BB Menthol",
        price: 50,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 6,
        name: "Canadian Classics Original",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 7,
        name: "Canadian Classics Silver",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 8,
        name: "Canadian Classics Ultra Blue",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 0 out of 5, Out of stock",
    },
    {
        id: 9,
        name: "Canadian Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 10,
        name: "Canadian Goose Blue Cigarettes",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 11,
        name: "Canadian Goose Red Cigarettes",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 12,
        name: "Canadian Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 13,
        name: "CANADIAN Menthol",
        price: 50,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 14,
        name: "Canadian Premium Original",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 0 out of 5, Out of stock",
    },
    {
        id: 15,
        name: "CANADIAN Ultra Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 16,
        name: "disCOUNT Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 17,
        name: "disCOUNT Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 18,
        name: "disCOUNT Menthol",
        price: 50,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 19,
        name: "DKs Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 20,
        name: "DKs Light",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 21,
        name: "Dumont Charcoal",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 0 out of 5, In stock",
    },
    {
        id: 22,
        name: "Dumont Extra Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 0 out of 5, In stock",
    },
    {
        id: 23,
        name: "duMont Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 24,
        name: "Dumont Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 25,
        name: "duMont Menthol",
        price: 50,
        info: "Cigarettes, Menthol Cigarettes, Rated 0 out of 5, In stock",
    },
    {
        id: 26,
        name: "ELITE Charcoal Cigarettes",
        price: 60,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 27,
        name: "ELITE Distinct Cigarettes",
        price: 60,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 28,
        name: "ELITE Full Cigarettes",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 29,
        name: "ELITE Ice Cigarettes",
        price: 60,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 30,
        name: "ELITE Lights Cigarettes",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 31,
        name: "ELITE Menthol Cigarettes",
        price: 60,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 32,
        name: "ELITE Signature Cigarettes",
        price: 60,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 33,
        name: "ELITE Ultra Lights Cigarettes",
        price: 60,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 34,
        name: "Nexus Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 0 out of 5, Out of stock",
    },
    {
        id: 35,
        name: "PlayFare’s Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 36,
        name: "Playfare’s Light",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 37,
        name: "Playfare’s Menthol",
        price: 50,
        info: "Cigarettes, Menthol Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 38,
        name: "PlayFare’s Ultra Light",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, Out of stock",
    },
    {
        id: 39,
        name: "Pop n Smoke – Blueberry Mint",
        price: 50,
        info: "Cigarettes, Bagged, Full Flavour, Light Cigarettes, Menthol Cigarettes, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 40,
        name: "Pop n Smoke – Grape",
        price: 50,
        info: "Cigarettes, Bagged, Full Flavour, Light Cigarettes, Menthol Cigarettes, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 41,
        name: "Pop n Smoke – Menthol",
        price: 50,
        info: "Cigarettes, Bagged, Full Flavour, Light Cigarettes, Menthol Cigarettes, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 42,
        name: "Pop n Smoke – Watermelon",
        price: 50,
        info: "Cigarettes, Bagged, Full Flavour, Light Cigarettes, Menthol Cigarettes, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 43,
        name: "PT Bag Little Cigars 200 – Cherry",
        price: 40,
        info: "Bagged, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 44,
        name: "PT Bag Little Cigars 200 – Grape",
        price: 40,
        info: "Bagged, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 45,
        name: "PT Bag Little Cigars 200 – Peaches & Cream",
        price: 40,
        info: "Bagged, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 46,
        name: "PT Bag Little Cigars 200 – Russian Cream",
        price: 40,
        info: "Bagged, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 47,
        name: "PT Bag Little Cigars 200 – Vanilla",
        price: 40,
        info: "Bagged, Cigars, Rated 0 out of 5, In stock",
    },
    {
        id: 48,
        name: "PT Bag Little Cigars 200 – Wild Berry",
        price: 40,
        info: "Bagged, Cigars, Rated 5.00 out of 5, In stock",
    },
    {
        id: 49,
        name: "Putter’s Light",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 50,
        name: "Rolled Gold Full",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 51,
        name: "Rolled Gold Lights",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 52,
        name: "SARATOGA Full Cigarettes",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 5.00 out of 5, In stock",
    },
    {
        id: 53,
        name: "SARATOGA Lights Cigarettes",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 5.00 out of 5, In stock",
    },
    {
        id: 54,
        name: "Time Blue",
        price: 50,
        info: "Cigarettes, Light Cigarettes, Rated 0 out of 5, Out of stock",
    },
    {
        id: 55,
        name: "Time Full Cigarettes",
        price: 50,
        info: "Cigarettes, Full Flavour, Rated 0 out of 5, Out of stock",
    }
];

export default products;